# Generated by Django 5.0.1 on 2024-01-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_perfil_dataend'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imgURL',
            field=models.TextField(default=None, null=True),
        ),
    ]
